### ISSUE TITLE
MiCaller

### ISSUE THREAD

**Issue by Owaiii** [infor-cloud/xtendm3#13]
Hello,

When i test MiCaller with CMS100MI Api. 

I have an error result => '{errorCause=mvx.app.ds.sCMS100MIRLst_MSHAPP002, errorMessage=Unable to load class mvx.app.ds.sCMS100MIRLst_MSHAPP002, error=true}'

Do you have a solution ? Thx.

**Comment by ErfanY** [comment]
Hi,

CMS100MI transactions are not supported through MiCaller. This should be done instead through ION API.
