### ISSUE TITLE
DBAction

### ISSUE THREAD

**Issue by Owaiii** [infor-cloud/xtendm3#9]
Hello,

In DBAction it is impossible to read from a recording. To create a reading by pagination in API xtendm3.
In M3 MAK it is possible to read with CHAIN and READE. It is a standard operation of the read data M3.
It will be possible to perform this type of reading in the future?

Thx.

Sincerely,
Owaiii

**Comment by ErfanY** [comment]
Hi @Owaiii 
Great question, I assume you're after a read operation where you can specify X number of records to be returned to support pagination. If that is the case, yes, we're working on adding support for that! 🙂

**Comment by Owaiii** [comment]
Great thanks a lot. :)
